### ISSUE TITLE
very good project but can you add other languages like english chinese japanese

### ISSUE THREAD

**Issue by aiastia** [AvenCores/openai-api-telegram-bot-public#2]

**Comment by AvenCores** [comment]
My bot is mainly aimed at the Russian-speaking audience, so I can't say for sure when translations into any other languages will appear.

**Comment by ghost** [comment]
Would you be ok and allow me to rewrite it in english?

**Comment by AvenCores** [comment]
> Would you be ok and allow me to rewrite it in english?

Ok
