### ISSUE TITLE
У меня проблема - i have a problem - sorunum var

### ISSUE THREAD

**Issue by tehlikex** [AvenCores/openai-api-telegram-bot-public#3]
RU :Здравствуйте, ваш проект очень хорош, и мне он нравится, но как настроить файл GPT4FREE и где я могу получить секретный ключ в файле botapiconfig.py, было бы очень хорошо, если бы вы опубликовали для него видео по установке и использованию
EN : hello your project is very nice and I like it but how to configure the GPT4FREE file and where can I get the secret key in the botapiconfig.py file it would be very good if you publish a installation and usage video for it
TR : merhaba projeniz çok güzel ve beğendim ama GPT4FREE dosyasını nasıl yapılandırılacak ve botapiconfig.py dosyadındaki secret keyi nereden nasıl alabilirim bunun için bir kurulum ve kullanım videosu yayınlamanız çok iyi olur

**Comment by AvenCores** [comment]
session_key - https://lmmsoft.github.io/openai_update_check_balance_api/
openaiapi - https://platform.openai.com/account/api-keys
telegrambotapi - t.me/BotFather
botname - username твоего бота без @

**Comment by tehlikex** [comment]
Прежде всего, спасибо за вашу поддержку, но я не знаю, как получить ключ сеанса, и я был бы признателен, если бы вы могли помочь с конфигурациями в файле под названием GPT4FREE

**Comment by AvenCores** [comment]
> GPT4FREE

Данная библиотека была удалена из-за устаревания
https://github.com/AvenCores/openai-api-telegram-bot-public/releases/tag/V1.3.0
